[project]
name = "template-creator"
version = "0.2.0"
dependencies = []

[tool.oaipkg]
disallow-dependents = true
ruff_full_check = false
unsafe-provides-packages = []

[tool.applied_manage]
blob_data = [
  "assets/icon.png",
  "assets/logo.png",
  "skills/template-creator/assets/site-preview.png",
]
blob_data_bazel_support = false

[tool.setuptools]
packages = []
py-modules = []
