load("//project/bazel/rules:python.bzl", "oai_py_library")

# gazelle:exclude skills/presentations/container_tools/slides_test.py

oai_py_library(
    name = "presentations",
    data = ["skills/presentations/agents/openai.yaml"],
    imports = ["."],
    src_excludes = [
        "**/*_test.py",
        "**/__main__.py",
        "**/conftest.py",
        "**/test_*.py",
        "manage/applied_spec.py",
        "manage/helm/**",
        "manage/kube/**",
        "setup.py",
    ],
    src_includes = ["**/*.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//pdf2image",
        "@pypi//pillow",
    ],
)
