[project]
name = "presentations"
version = "0.1.13"
dependencies = [
  "Pillow",
  "pdf2image",
]

[tool.oaipkg]
disallow-dependents = true
ruff_full_check = false
unsafe-provides-packages = []
dependency-check-ignore = [
  "ensure-raster-image",
  "runtime-helpers",
]

[tool.applied_manage]
blob_data = [
  "assets/icon.png",
  "assets/logo.png",
]
blob_data_bazel_support = false

[tool.setuptools]
packages = []
py-modules = []
